### PR TITLE
Use qt-main and 3.15.3

### PR DESCRIPTION
**Pull request by SrNetoChan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
Hmmm what is actually failing here?

**Comment by SrNetoChan** [comment]
> Hmmm what is actually failing here?

@gillins I think OSX is quitting on errors during make. But linux is giving an error saying that it can't find the make command.

**Comment by gillins** [comment]
I think adding `make  # [unix]` to the build section will fix this. Not sure how it was working before...

**Comment by SrNetoChan** [comment]
> I think adding `make # [unix]` to the build section will fix this. Not sure how it was working before...

@gillins maybe the docker image already had make installed by default?

**Comment by gillins** [comment]
> maybe the docker image already had make installed by default?

Yes I think you are right - it used to but got removed recently. Not sure about the errors you now have. I think the `glibc` error is related to older CentOS that is the default for building but I think `qt` now requires a more recent version. Not sure how to request it.....

**Comment by SrNetoChan** [comment]
I will try to see other qt based recipes to see if I can find something.

Thanks for your help. I am a bit useless in this matter :-)

**Comment by gillins** [comment]
> I will try to see other qt based recipes to see if I can find something.

Thanks! I'm so out of the loop now I'm not really up with what is happening. Hopefully I'll have more time in a couple of weeks to help if you haven't sorted it out by then.

**Comment by SrNetoChan** [comment]
@conda-forge-admin, please rerender

**Comment by SrNetoChan** [comment]
Superseeded by #11. Closing

**Pull request closed without merging**
